In [ ]:
# Introduction to ML Models -----   >
# (1). Supervised Models --- > In this model , we will train our labelled data .
# Ex. --- > LinearRegressin , LogisticRegression , DecisionTree , RandomForest
# (2). UnSupervised Models ---- > In this model, we will train our unlabelled data .
# Ex. --- > KMeans, PCA

In [ ]:
# Data -------->
# (1). Descrete data --- > LogisticRegression , Decisiontreeclassifier , randomforestclassifier
# (2). Continous data --- > LinearRegression , DecisiontreeRegressor , RandomForestRegressor

In [ ]:
# Workflow of ML MOdels

# Data Import --- > Data Cleaning and Preprocessing --- > Select ML Model based on target data ---- > Model training --- >
# Model prediction ----- > Model Performance Evaluation .

In [ ]:
# (1). LinearRegression Model --- > when our target data is numerical .

In [ ]:
import pandas as pd

In [ ]:
df  = pd.read_csv("/content/insurance - insurance.csv")
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [ ]:
x = df.drop(columns=['charges'])
y = df['charges']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
x['sex']=le.fit_transform(x['sex'])
x['smoker']=le.fit_transform(x['smoker'])
x['region']=le.fit_transform(x['region'])

In [ ]:
x.head(3)

   age  sex    bmi  children  smoker  region
0   19    0  27.90         0       1       3
1   18    1  33.77         1       0       2
2   28    1  33.00         3       0       2

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
# Steps-3 ---> select ml model (LinearRegression)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

# r2_score ---> if data is numerical
# Accuracy Score ---> if data is categorial

In [ ]:
r2_score(y_test, y_pred)

0.7833463107364539

In [ ]:
# CREDIT-SCORE DATASET----->

In [ ]:
df  = pd.read_csv("/content/credit_scoring - credit_scoring.csv")
df.head(3)

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771,6,957000,2.76,12,Auto Loan

In [ ]:
# df.isnull().sum()

In [ ]:
x = df.drop(columns=['Loan Amount'])
y = df['Loan Amount']

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
x['Gender']=le.fit_transform(x['Gender'])
x['Marital Status']=le.fit_transform(x['Marital Status'])
x['Education Level']=le.fit_transform(x['Education Level'])
x['Employment Status']=le.fit_transform(x['Employment Status'])
x['Type of Loan']=le.fit_transform(x['Type of Loan'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test, y_pred)

-0.050740459000434335

In [ ]:
# CARS DATASET ----->

In [ ]:
df = pd.read_csv("/content/cars - cars.csv")

In [ ]:
df.head(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC BSII,1992,50000,100000,Petrol,Individual,Manual,Fourth & Above Owner
1,Maruti Gypsy E MG410W ST,1995,95000,100000,Petrol,Individual,Manual,Second Owner
2,Mahindra Jeep CL 500 MDI,1996,250000,35000,Diesel,Individual,Manual,Second Owner

In [ ]:
# df.isnull().sum()

In [ ]:
x = df.drop(columns=['km_driven'])
y = df['km_driven']

In [ ]:
x['name']=le.fit_transform(x['name'])
x['fuel']=le.fit_transform(x['fuel'])
x['seller_type']=le.fit_transform(x['seller_type'])
x['transmission']=le.fit_transform(x['transmission'])
x['owner']=le.fit_transform(x['owner'])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
lr = LinearRegression

In [ ]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
r2_score(y_test, y_pred)

0.37089139683265104